# Site settings
title: Akif Hatipoğlu
description: 'Welcome to my page'
url: 'akifhatipoglu.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Akif Hatipoğlu'
  email: akifhatipoglu.tech@gmail.com
  twitter_username: ufocanakf
  facebook_username: akif.hatipoglu.5
  github_username:  akifhatipoglu
  linkedin_username:  akif-hatipoğlu-psm-i-b3129351
  instagram_username:  hatipogluakif

defaults:
  -
    scope:
      path: ''
      type: 'page'
    values:
        layout: 'page'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
