# Welcome to Jekyll!
#

# Site settings
title: Akif Hatipoğlu
description: |
  Another fine responsive  
  site template freebie  
  crafted by [Akif Hatipoğlu]
owner: Akif Hatipoğlu
first_published: 2016 # if migrating another site, the year of your first publish
email: akifhatipoglu.tech@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://akifhatipoglu.github.io" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/akifhatipoglu
  linkedin-square: https://tr.linkedin.com/in/akif-hatipoğlu-psm-i-b3129351
  facebook-official: https://www.facebook.com/akif.hatipoglu.5
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: akifhatipoglu.tech@gmail.com
  #flickr:
  instagram: https://www.instagram.com/hatipogluakif/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
